language: python
python:
  - "2.7"
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install pip --upgrade
  - pip install setuptools
  - python setup.py sdist
  - pip install dist/ga4gh_client*.tar.gz
  - wget https://protobuf.googlecode.com/files/protobuf-2.4.1.tar.gz
  - tar -xzvf protobuf-2.4.1.tar.gz
  - pushd protobuf-2.4.1 && ./configure --prefix=/usr && make && sudo make install && popd
  - pip list
  - git clone https://github.com/protobuf-c/protobuf-c.git && cd protobuf-c && ./autogen.sh && ./configure && make && sudo make install
  - protoc --version
  - pip install -r requirements.txt -c constraints.txt --upgrade --no-cache-dir
# every installable in setup.py's entry_points should be tested here
  - pip list
  - ga4gh_client --version

before_script:
  - pip install -r dev-requirements.txt -c constraints.txt

# run_tests.py runs everything under the script: tag so only put commands
# under it that we want to run (and want to be able to run) as local tests
script: 
  - flake8 client_dev.py setup.py tests ga4gh scripts
  - python -mnose tests
              --with-coverage --cover-package ga4gh.client
              --cover-inclusive --cover-min-percentage=50
              --cover-branches --cover-erase
  - make clean -C docs
  - make html -C docs

after_success:
# run codecov
  - bash <(curl -s https://codecov.io/bash)
